### ISSUE TITLE
Translate web application into Spanish

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/renters-rights#38]
Interested in contributing? Join our[ Slack](https://slackin-c4sj.herokuapp.com/)  - renters-rights channel. We are discussing how to approach this issue on slack. 

If you're in the bay area, you are welcome to join us at our next [hack night](https://meetup.com/code-for-san-jose) on Thursday Oct 12 at Bower Institute. We usually meet two Thursdays a month.

**Comment by bsemexan** [comment]
I would like to help, but I don't know where to start

**Comment by ychoy** [comment]
Hi @bsemexan thanks for your response! Can you join our [Slack](http://codeforsanjose.slack.com/) and join the renters-rights channel? I don't know yet how to approach this but would like you to join our discussion. You are also welcome to join us at our next hack night on Thursday Oct 12 at Bower Institute. [RSVP](https://www.meetup.com/Code-for-San-Jose/) We usually meet two Thursdays a month.

**Comment by bsemexan** [comment]
I'm in Oregon. I found this thru hacktoberfest.

**Comment by frangelh** [comment]
Hey there, I would like to help. I am a native spanish speaker from Dominica Republic :)

**Comment by bsemexan** [comment]
Nice, a native speaker. That should help help

**Comment by ychoy** [comment]
Hi @frangelh can you join our [slack](https://slackin-c4sj.herokuapp.com/) renters-rights channel? Currently need some help with FAQ page. For the other webpages we ware most likely updating the content within next month. Let's continue our conversation on slack.

**Comment by ychoy** [comment]
Thanks @frangelh  @bsemexan and Jonathan  for your help on translating the FAQ page. I'm closing this issue for now because after further discussion we won't be able to implement translation until we determine the next iteration of our web app, which will most likely change the language of our webpages.

**Comment by ychoy** [comment]
Thanks @frangelh @bsemexan and Jonathan for your help on translating the FAQ page.

Closing for now because after further discussion we won't be able to implement translation until we determine the next iteration of our web app, which will most likely change the language of our webpages.
