### ISSUE TITLE
Translate web application into Chinese

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/renters-rights#40]
Interested in contributing? Join our[ Slack](https://slackin-c4sj.herokuapp.com/)  - renters-rights channel. We are discussing how to approach this issue on slack. 

If you're in the bay area, you are welcome to join us at our next [hack night](https://meetup.com/code-for-san-jose) on Thursday Oct 12 at Bower Institute. We usually meet two Thursdays a month.

**Comment by tcburns24** [comment]
@ychoy 1st draft of English-to-Chinese is complete. [https://docs.google.com/spreadsheets/d/1WSayRH9Ko9Qa3EnSO46IXZ5bjr1-FgBgVavShXSC7OM/edit#gid=0](url)

**Comment by ychoy** [comment]
Thanks @tcburns24  this looks great. Will keep you posted when we're done with next iteration of the web application for further translation.

**Comment by ychoy** [comment]
Closing for now because after further discussion we won't be able to implement translation until we determine the next iteration of our web app, which will most likely change the language of our webpages.

**Comment by aszheng** [comment]
@ychoy 

Can I start working on this next? Would like access to the google sheet mentioned above. Thanks!

**Comment by easherma** [comment]
Just chiming in from Chicago to point out that, if we make the app easy to translate into other languages, that should also in theory make it easy to 'translate' the content to other cities as well! Would love to help get some people together to make this happen if feasible. (I'm interested in forking this project off for Chicago)

**Comment by ychoy** [comment]
@easherma Good point, I'll chat with our team to see what we can do about this.
