### ISSUE TITLE
Translate web application into Tagalog

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/renters-rights#41]
If you are interested, please join our[ Slack](https://slackin-c4sj.herokuapp.com/) renters-rights channel. We are discussing how to approach this issue on slack. If you're in the bay area, you are welcome to join us at our next [hack night](https://meetup.com/code-for-san-jose) on Thursday Oct 12 at Bower Institute. We usually meet two Thursdays a month.

**Comment by francistaberdo** [comment]
I would like to be a part of this 💯

**Comment by ychoy** [comment]
Awesome! Can you join our[ Slack](https://codeforsanjose.slack.com) and join the renters-rights channel? We are discussing how to approach this issue on slack. If you're in the bay area, you are welcome to join us at our next [hack night](https://meetup.com/code-for-san-jose) on Thursday Oct 12 at Bower Institute. We usually meet two Thursdays a month.

**Comment by ychoy** [comment]
Closing for now because after further discussion we won't be able to implement translation until we determine the next iteration of our web app, which will most likely change the language of our webpages.
