### ISSUE TITLE
Email Form

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/renters-rights#68]
Create an email form that takes inputted data and pops up email client. Make it work with various email clients on desktop and mobile. The email should be directed to the Renter's Rights & Referrals Program: rrrp@sanjoseca.gov

**Comment by mishraak** [comment]
Sorry, I took the liberty to work on this idea without asking in prior if anybody was working on this or not and without confirming the user input fields (but should be quiet flexible to modify). I have raised a PR but feel free to let me know the details of input format so I can modify current email and form and raise another PR. Also, is it okay to use some 3rd party library like EmailJS to be used for the purpose?
